"""
Razorpay Payment Execution Provider Abstraction for RecoverAI.
Supports Simulation Provider (default test mode) and Razorpay Test Mode Provider.
Does NOT perform real-money transactions.
"""

import os
import hashlib
from abc import ABC, abstractmethod
from typing import Tuple, Optional
from app.models.revenue_event import RevenueEvent
from app.models.customer import Customer
from app.ai.strategy import RecoveryStrategy
from app.core.config import settings


class BaseRecoveryProvider(ABC):
    @abstractmethod
    def execute_recovery(
        self,
        event: RevenueEvent,
        customer: Customer,
        strategy: RecoveryStrategy,
        recovery_probability: float,
        attempt_number: int = 1
    ) -> Tuple[str, Optional[str], Optional[str], str, int]:
        """
        Execute recovery action.
        Returns: (status ['SUCCESS', 'FAILED'], result_code, error_message, provider_ref, amount_recovered_paise)
        """
        pass


class SimulationRecoveryProvider(BaseRecoveryProvider):
    """
    Deterministic Seeded Simulation Engine for buildathon demo.
    Outcome is generated by comparing a deterministic hash draw against ML recovery probability.
    """
    def execute_recovery(
        self,
        event: RevenueEvent,
        customer: Customer,
        strategy: RecoveryStrategy,
        recovery_probability: float,
        attempt_number: int = 1
    ) -> Tuple[str, Optional[str], Optional[str], str, int]:
        # Deterministic seed draw derived from event ID + attempt_number
        seed_str = f"{event.id}_{attempt_number}_{strategy.value}"
        hash_val = int(hashlib.md5(seed_str.encode("utf-8")).hexdigest(), 16)
        normalized_draw = (hash_val % 10000) / 10000.0  # 0.0 to 0.9999

        provider_ref = f"sim_ref_{hashlib.sha256(seed_str.encode('utf-8')).hexdigest()[:12]}"

        # Seeded outcome check
        if normalized_draw < recovery_probability:
            return (
                "SUCCESS",
                "SIM_RECOVERED_SUCCESS",
                None,
                provider_ref,
                event.amount
            )
        else:
            reasons = [
                "SIM_CUSTOMER_DECLINED_RETRY",
                "SIM_BANK_AUTHORIZATION_FAILED",
                "SIM_LINK_EXPIRED_UNPAID",
                "SIM_INSUFFICIENT_FUNDS_RETRY"
            ]
            error_code = reasons[hash_val % len(reasons)]
            return (
                "FAILED",
                error_code,
                f"Simulated payment attempt failed: {error_code}",
                provider_ref,
                0
            )


class RazorpayTestProvider(BaseRecoveryProvider):
    """
    Razorpay Test Mode Provider abstraction.
    Uses Razorpay Test Mode Keys to create simulated Payment Links or Subscription retries.
    """
    def execute_recovery(
        self,
        event: RevenueEvent,
        customer: Customer,
        strategy: RecoveryStrategy,
        recovery_probability: float,
        attempt_number: int = 1
    ) -> Tuple[str, Optional[str], Optional[str], str, int]:
        key_id = getattr(settings, "RAZORPAY_KEY_ID", "rzp_test_placeholder")
        provider_ref = f"plink_test_{event.id[:8]}_{attempt_number}"

        if strategy == RecoveryStrategy.PAYMENT_LINK:
            # Simulate Razorpay Payment Link creation response
            return (
                "SUCCESS",
                "RAZORPAY_LINK_CREATED",
                None,
                provider_ref,
                event.amount
            )
        else:
            # Fallback to simulation execution for non-link test strategies
            sim = SimulationRecoveryProvider()
            return sim.execute_recovery(event, customer, strategy, recovery_probability, attempt_number)


def get_recovery_provider() -> BaseRecoveryProvider:
    """Factory function returning configured recovery provider."""
    mode = os.getenv("PAYMENT_EXECUTION_MODE", "simulation").lower()
    if mode == "razorpay_test":
        return RazorpayTestProvider()
    return SimulationRecoveryProvider()
