"""Initial models

Revision ID: 67b2a8054fd4
Revises: None
Create Date: 2026-08-30 16:27:38.653246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67b2a8054fd4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('business_type', sa.String(length=100), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('customers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('total_spent_paise', sa.BigInteger(), nullable=False),
    sa.Column('successful_tx_count', sa.Integer(), nullable=False),
    sa.Column('failed_tx_count', sa.Integer(), nullable=False),
    sa.Column('opt_out', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=False)
    op.create_index(op.f('ix_customers_merchant_id'), 'customers', ['merchant_id'], unique=False)
    op.create_table('revenue_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('days_overdue', sa.Integer(), nullable=False),
    sa.Column('transaction_count', sa.Integer(), nullable=False),
    sa.Column('successful_transaction_count', sa.Integer(), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revenue_events_customer_id'), 'revenue_events', ['customer_id'], unique=False)
    op.create_index(op.f('ix_revenue_events_event_type'), 'revenue_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_revenue_events_merchant_id'), 'revenue_events', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_revenue_events_status'), 'revenue_events', ['status'], unique=False)
    op.create_table('recovery_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('revenue_event_id', sa.String(length=36), nullable=False),
    sa.Column('strategy', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('initiated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_code', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['revenue_event_id'], ['revenue_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_attempts_revenue_event_id'), 'recovery_attempts', ['revenue_event_id'], unique=False)
    op.create_index(op.f('ix_recovery_attempts_status'), 'recovery_attempts', ['status'], unique=False)
    op.create_table('risk_assessments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('revenue_event_id', sa.String(length=36), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('recovery_probability', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('revenue_at_risk_paise', sa.BigInteger(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['revenue_event_id'], ['revenue_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_assessments_revenue_event_id'), 'risk_assessments', ['revenue_event_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('revenue_event_id', sa.String(length=36), nullable=False),
    sa.Column('recovery_attempt_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('policy_result', sa.String(length=50), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('amount_recovered_paise', sa.BigInteger(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recovery_attempt_id'], ['recovery_attempts.id'], ),
    sa.ForeignKeyConstraint(['revenue_event_id'], ['revenue_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_revenue_event_id'), 'audit_logs', ['revenue_event_id'], unique=False)
    op.create_table('recovery_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('recovery_attempt_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recovery_attempt_id'], ['recovery_attempts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_events_recovery_attempt_id'), 'recovery_events', ['recovery_attempt_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recovery_events_recovery_attempt_id'), table_name='recovery_events')
    op.drop_table('recovery_events')
    op.drop_index(op.f('ix_audit_logs_revenue_event_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_risk_assessments_revenue_event_id'), table_name='risk_assessments')
    op.drop_table('risk_assessments')
    op.drop_index(op.f('ix_recovery_attempts_status'), table_name='recovery_attempts')
    op.drop_index(op.f('ix_recovery_attempts_revenue_event_id'), table_name='recovery_attempts')
    op.drop_table('recovery_attempts')
    op.drop_index(op.f('ix_revenue_events_status'), table_name='revenue_events')
    op.drop_index(op.f('ix_revenue_events_merchant_id'), table_name='revenue_events')
    op.drop_index(op.f('ix_revenue_events_event_type'), table_name='revenue_events')
    op.drop_index(op.f('ix_revenue_events_customer_id'), table_name='revenue_events')
    op.drop_table('revenue_events')
    op.drop_index(op.f('ix_customers_merchant_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_table('customers')
    op.drop_table('merchants')
    # ### end Alembic commands ###
