"""Add composite indexes

Revision ID: cb34d6f5fa41
Revises: '67b2a8054fd4'
Create Date: 2026-08-31 21:20:39.394810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb34d6f5fa41'
down_revision: Union[str, None] = '67b2a8054fd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_revenue_events_merchant_status', 'revenue_events', ['merchant_id', 'status'], unique=False)
    op.create_index('ix_revenue_events_merchant_type', 'revenue_events', ['merchant_id', 'event_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_revenue_events_merchant_type', table_name='revenue_events')
    op.drop_index('ix_revenue_events_merchant_status', table_name='revenue_events')
    # ### end Alembic commands ###
